import { Injectable } from '@angular/core';
import { of } from 'rxjs';

export interface Recipe {
  id: number;
  slug: string;
  title: string;
  description: string;
  introduction: string;
  category: string;
  cuisine: string;
  prepTime: string;
  cookTime: string;
  totalTime: string;
  servings: number;
  difficulty: string;
  ingredients: string[];
  instructions: string[];
  tips: string[];
  image: string;
  imageAlt: string;
  seoTitle: string;
  seoDescription: string;
  isVeg: boolean;
  price?: number;
}

@Injectable({
  providedIn: 'root'
})
export class RecipeService {
  private recipes: Recipe[] = [
    {
        "id": 1,
        "slug": "south-indian-poha-full",
        "title": "South Indian Poha (Full)",
        "description": "A delightful twist on the classic poha, this South Indian version features soft, flavorful poha.",
        "introduction": "A delightful twist on the classic poha, this South Indian version features soft, flavorful poha.",
        "category": "Main Course",
        "cuisine": "Indian",
        "prepTime": "10 mins",
        "cookTime": "15 mins",
        "totalTime": "25 mins",
        "servings": 1,
        "difficulty": "Easy",
        "ingredients": [],
        "instructions": [],
        "tips": [],
        "image": "https://b.zmtcdn.com/data/dish_photos/c28/d1b40e1aa8609b995caf2e3f11ba6c28.jpeg",
        "imageAlt": "South Indian Poha (Full)",
        "seoTitle": "South Indian Poha (Full) | Foody Bhai",
        "seoDescription": "A delightful twist on the classic poha, this South Indian version features soft, flavorful poha.",
        "isVeg": true,
        "price": 109
    },
    {
        "id": 2,
        "slug": "paneer-butter-masala",
        "title": "Paneer Butter Masala",
        "description": "Paneer cubes in a creamy tomato gravy, flavored with aromatic spices.",
        "introduction": "Paneer cubes in a creamy tomato gravy, flavored with aromatic spices.",
        "category": "Main Course",
        "cuisine": "Indian",
        "prepTime": "10 mins",
        "cookTime": "15 mins",
        "totalTime": "25 mins",
        "servings": 1,
        "difficulty": "Easy",
        "ingredients": [],
        "instructions": [],
        "tips": [],
        "image": "https://b.zmtcdn.com/data/dish_photos/ba7/af5a2bd5e1a6587c9981ea0beadc4ba7.jpeg",
        "imageAlt": "Paneer Butter Masala",
        "seoTitle": "Paneer Butter Masala | Foody Bhai",
        "seoDescription": "Paneer cubes in a creamy tomato gravy, flavored with aromatic spices.",
        "isVeg": true,
        "price": 229
    },
    {
        "id": 3,
        "slug": "dal-tadka",
        "title": "Dal Tadka",
        "description": "Lentils tempered with garlic, cumin and red chilli, served with steamed rice.",
        "introduction": "Lentils tempered with garlic, cumin and red chilli, served with steamed rice.",
        "category": "Main Course",
        "cuisine": "Indian",
        "prepTime": "10 mins",
        "cookTime": "15 mins",
        "totalTime": "25 mins",
        "servings": 1,
        "difficulty": "Easy",
        "ingredients": [],
        "instructions": [],
        "tips": [],
        "image": "https://b.zmtcdn.com/data/dish_photos/bc6/e777b20df7aad899b9f750203b49dbc6.jpeg",
        "imageAlt": "Dal Tadka",
        "seoTitle": "Dal Tadka | Foody Bhai",
        "seoDescription": "Lentils tempered with garlic, cumin and red chilli, served with steamed rice.",
        "isVeg": true,
        "price": 199
    },
    {
        "id": 4,
        "slug": "dal-fry",
        "title": "Dal Fry",
        "description": "A comforting Indian classic made with perfectly cooked lentils, tempered with aromatic spices.",
        "introduction": "A comforting Indian classic made with perfectly cooked lentils, tempered with aromatic spices.",
        "category": "Main Course",
        "cuisine": "Indian",
        "prepTime": "10 mins",
        "cookTime": "15 mins",
        "totalTime": "25 mins",
        "servings": 1,
        "difficulty": "Easy",
        "ingredients": [],
        "instructions": [],
        "tips": [],
        "image": "https://b.zmtcdn.com/data/dish_photos/e5f/b2849d858dedd53dbfea3a377ac7be5f.jpg",
        "imageAlt": "Dal Fry",
        "seoTitle": "Dal Fry | Foody Bhai",
        "seoDescription": "A comforting Indian classic made with perfectly cooked lentils, tempered with aromatic spices.",
        "isVeg": true,
        "price": 179
    },
    {
        "id": 5,
        "slug": "aloo-jeera-masala",
        "title": "Aloo Jeera Masala",
        "description": "A simple yet flavorful Indian dish made with boiled potatoes and aromatic cumin.",
        "introduction": "A simple yet flavorful Indian dish made with boiled potatoes and aromatic cumin.",
        "category": "Main Course",
        "cuisine": "Indian",
        "prepTime": "10 mins",
        "cookTime": "15 mins",
        "totalTime": "25 mins",
        "servings": 1,
        "difficulty": "Easy",
        "ingredients": [],
        "instructions": [],
        "tips": [],
        "image": "https://b.zmtcdn.com/data/dish_photos/c75/f3df03ef4ac0fcc1433dd08a4e60fc75.jpg",
        "imageAlt": "Aloo Jeera Masala",
        "seoTitle": "Aloo Jeera Masala | Foody Bhai",
        "seoDescription": "A simple yet flavorful Indian dish made with boiled potatoes and aromatic cumin.",
        "isVeg": true,
        "price": 79
    },
    {
        "id": 6,
        "slug": "paneer-do-pyaaza",
        "title": "Paneer Do Pyaaza",
        "description": "A classic North Indian delicacy offering a perfect balance of tangy, spicy and flavorful notes.",
        "introduction": "A classic North Indian delicacy offering a perfect balance of tangy, spicy and flavorful notes.",
        "category": "Main Course",
        "cuisine": "Indian",
        "prepTime": "10 mins",
        "cookTime": "15 mins",
        "totalTime": "25 mins",
        "servings": 1,
        "difficulty": "Easy",
        "ingredients": [],
        "instructions": [],
        "tips": [],
        "image": "https://b.zmtcdn.com/data/dish_photos/1ca/6eab6398e4ec2a0594910f77b0cf51ca.jpg",
        "imageAlt": "Paneer Do Pyaaza",
        "seoTitle": "Paneer Do Pyaaza | Foody Bhai",
        "seoDescription": "A classic North Indian delicacy offering a perfect balance of tangy, spicy and flavorful notes.",
        "isVeg": true,
        "price": 249
    },
    {
        "id": 7,
        "slug": "paneer-lababdar",
        "title": "Paneer Lababdar",
        "description": "A mildly spiced, velvety North Indian delicacy that pairs beautifully with Indian breads or rice.",
        "introduction": "A mildly spiced, velvety North Indian delicacy that pairs beautifully with Indian breads or rice.",
        "category": "Main Course",
        "cuisine": "Indian",
        "prepTime": "10 mins",
        "cookTime": "15 mins",
        "totalTime": "25 mins",
        "servings": 1,
        "difficulty": "Easy",
        "ingredients": [],
        "instructions": [],
        "tips": [],
        "image": "https://b.zmtcdn.com/data/dish_photos/18e/89d82153a01471a13451c7a44e85118e.jpg",
        "imageAlt": "Paneer Lababdar",
        "seoTitle": "Paneer Lababdar | Foody Bhai",
        "seoDescription": "A mildly spiced, velvety North Indian delicacy that pairs beautifully with Indian breads or rice.",
        "isVeg": true,
        "price": 229
    },
    {
        "id": 8,
        "slug": "peri-peri-fries",
        "title": "Peri Peri Fries",
        "description": "Crispy golden fries tossed in spicy and flavorful peri peri seasoning.",
        "introduction": "Crispy golden fries tossed in spicy and flavorful peri peri seasoning.",
        "category": "Main Course",
        "cuisine": "Indian",
        "prepTime": "10 mins",
        "cookTime": "15 mins",
        "totalTime": "25 mins",
        "servings": 1,
        "difficulty": "Easy",
        "ingredients": [],
        "instructions": [],
        "tips": [],
        "image": "https://b.zmtcdn.com/data/dish_photos/84a/4e95df262694e22d62e5712895bb184a.jpeg",
        "imageAlt": "Peri Peri Fries",
        "seoTitle": "Peri Peri Fries | Foody Bhai",
        "seoDescription": "Crispy golden fries tossed in spicy and flavorful peri peri seasoning.",
        "isVeg": true,
        "price": 119
    },
    {
        "id": 9,
        "slug": "matar-paneer",
        "title": "Matar Paneer",
        "description": "Soft paneer cubes and tender green peas cooked in a rich, flavorful tomato gravy.",
        "introduction": "Soft paneer cubes and tender green peas cooked in a rich, flavorful tomato gravy.",
        "category": "Main Course",
        "cuisine": "Indian",
        "prepTime": "10 mins",
        "cookTime": "15 mins",
        "totalTime": "25 mins",
        "servings": 1,
        "difficulty": "Easy",
        "ingredients": [],
        "instructions": [],
        "tips": [],
        "image": "https://b.zmtcdn.com/data/dish_photos/eb7/875cdd2028a0a80dd7826e32be1c3eb7.jpeg",
        "imageAlt": "Matar Paneer",
        "seoTitle": "Matar Paneer | Foody Bhai",
        "seoDescription": "Soft paneer cubes and tender green peas cooked in a rich, flavorful tomato gravy.",
        "isVeg": true,
        "price": 209
    },
    {
        "id": 10,
        "slug": "aloo-sabzi-with-gravy",
        "title": "Aloo Sabzi with Gravy",
        "description": "Soft, tender potatoes cooked in a flavorful, aromatic onion-tomato gravy with traditional Indian spices.",
        "introduction": "Soft, tender potatoes cooked in a flavorful, aromatic onion-tomato gravy with traditional Indian spices.",
        "category": "Main Course",
        "cuisine": "Indian",
        "prepTime": "10 mins",
        "cookTime": "15 mins",
        "totalTime": "25 mins",
        "servings": 1,
        "difficulty": "Easy",
        "ingredients": [],
        "instructions": [],
        "tips": [],
        "image": "https://b.zmtcdn.com/data/dish_photos/079/6680db214f10f47d7a68c9bd247bd079.jpg",
        "imageAlt": "Aloo Sabzi with Gravy",
        "seoTitle": "Aloo Sabzi with Gravy | Foody Bhai",
        "seoDescription": "Soft, tender potatoes cooked in a flavorful, aromatic onion-tomato gravy with traditional Indian spices.",
        "isVeg": true,
        "price": 99
    },
    {
        "id": 11,
        "slug": "4-puri-aloo-sabzi",
        "title": "4 Puri + Aloo Sabzi",
        "description": "4 hot and fluffy puris served with delicious, mildly spiced aloo sabzi.",
        "introduction": "4 hot and fluffy puris served with delicious, mildly spiced aloo sabzi.",
        "category": "Puri & Sabzi",
        "cuisine": "Indian",
        "prepTime": "10 mins",
        "cookTime": "15 mins",
        "totalTime": "25 mins",
        "servings": 1,
        "difficulty": "Easy",
        "ingredients": [],
        "instructions": [],
        "tips": [],
        "image": "https://b.zmtcdn.com/data/dish_photos/f6d/b46b6b03af99bc15deb96f4f24fdff6d.jpeg",
        "imageAlt": "4 Puri + Aloo Sabzi",
        "seoTitle": "4 Puri + Aloo Sabzi | Foody Bhai",
        "seoDescription": "4 hot and fluffy puris served with delicious, mildly spiced aloo sabzi.",
        "isVeg": true,
        "price": 99
    },
    {
        "id": 12,
        "slug": "6-puri-aloo-sabzi",
        "title": "6 Puri + Aloo Sabzi",
        "description": "6 freshly prepared puris paired with flavorful aloo sabzi.",
        "introduction": "6 freshly prepared puris paired with flavorful aloo sabzi.",
        "category": "Puri & Sabzi",
        "cuisine": "Indian",
        "prepTime": "10 mins",
        "cookTime": "15 mins",
        "totalTime": "25 mins",
        "servings": 1,
        "difficulty": "Easy",
        "ingredients": [],
        "instructions": [],
        "tips": [],
        "image": "https://b.zmtcdn.com/data/dish_photos/da1/c6655bd826cf05a4267d377b27c41da1.jpeg",
        "imageAlt": "6 Puri + Aloo Sabzi",
        "seoTitle": "6 Puri + Aloo Sabzi | Foody Bhai",
        "seoDescription": "6 freshly prepared puris paired with flavorful aloo sabzi.",
        "isVeg": true,
        "price": 119
    },
    {
        "id": 13,
        "slug": "6-puri-sabzi-raita",
        "title": "6 Puri + Sabzi + Raita",
        "description": "Hot and fluffy puris with homestyle aloo sabzi, served with refreshing creamy raita.",
        "introduction": "Hot and fluffy puris with homestyle aloo sabzi, served with refreshing creamy raita.",
        "category": "Puri & Sabzi",
        "cuisine": "Indian",
        "prepTime": "10 mins",
        "cookTime": "15 mins",
        "totalTime": "25 mins",
        "servings": 1,
        "difficulty": "Easy",
        "ingredients": [],
        "instructions": [],
        "tips": [],
        "image": "https://b.zmtcdn.com/data/dish_photos/4fe/a98e23e8a6deff06f7bc0661f85ec4fe.jpeg",
        "imageAlt": "6 Puri + Sabzi + Raita",
        "seoTitle": "6 Puri + Sabzi + Raita | Foody Bhai",
        "seoDescription": "Hot and fluffy puris with homestyle aloo sabzi, served with refreshing creamy raita.",
        "isVeg": true,
        "price": 139
    },
    {
        "id": 14,
        "slug": "4-special-puri-sabzi",
        "title": "4 Special Puri + Sabzi",
        "description": "A special Foody Bhai-style puri meal with crispy puris and flavorful masala aloo sabzi.",
        "introduction": "A special Foody Bhai-style puri meal with crispy puris and flavorful masala aloo sabzi.",
        "category": "Puri & Sabzi",
        "cuisine": "Indian",
        "prepTime": "10 mins",
        "cookTime": "15 mins",
        "totalTime": "25 mins",
        "servings": 1,
        "difficulty": "Easy",
        "ingredients": [],
        "instructions": [],
        "tips": [],
        "image": "https://b.zmtcdn.com/data/dish_photos/ded/ea86fccbddd7e4ed927ade555de1cded.jpeg",
        "imageAlt": "4 Special Puri + Sabzi",
        "seoTitle": "4 Special Puri + Sabzi | Foody Bhai",
        "seoDescription": "A special Foody Bhai-style puri meal with crispy puris and flavorful masala aloo sabzi.",
        "isVeg": true,
        "price": 129
    },
    {
        "id": 15,
        "slug": "steam-rice",
        "title": "Steam Rice",
        "description": "Special boiled rice in home cooked style.",
        "introduction": "Special boiled rice in home cooked style.",
        "category": "Rice",
        "cuisine": "Indian",
        "prepTime": "10 mins",
        "cookTime": "15 mins",
        "totalTime": "25 mins",
        "servings": 1,
        "difficulty": "Easy",
        "ingredients": [],
        "instructions": [],
        "tips": [],
        "image": "https://b.zmtcdn.com/data/dish_photos/139/f85b75996f17e3e9ae90d0cd420a8139.png",
        "imageAlt": "Steam Rice",
        "seoTitle": "Steam Rice | Foody Bhai",
        "seoDescription": "Special boiled rice in home cooked style.",
        "isVeg": true,
        "price": 79
    },
    {
        "id": 16,
        "slug": "jeera-rice",
        "title": "Jeera Rice",
        "description": "Fragrant, long grain basmati rice cooked to perfection and tempered with earthy cumin.",
        "introduction": "Fragrant, long grain basmati rice cooked to perfection and tempered with earthy cumin.",
        "category": "Rice",
        "cuisine": "Indian",
        "prepTime": "10 mins",
        "cookTime": "15 mins",
        "totalTime": "25 mins",
        "servings": 1,
        "difficulty": "Easy",
        "ingredients": [],
        "instructions": [],
        "tips": [],
        "image": "https://b.zmtcdn.com/data/dish_photos/367/2b1a15c33fcb7d6a1c91f9bff6677367.jpg",
        "imageAlt": "Jeera Rice",
        "seoTitle": "Jeera Rice | Foody Bhai",
        "seoDescription": "Fragrant, long grain basmati rice cooked to perfection and tempered with earthy cumin.",
        "isVeg": true,
        "price": 89
    },
    {
        "id": 17,
        "slug": "fried-rice",
        "title": "Fried Rice",
        "description": "Aromatic basmati rice stir fried with fresh vegetables, flavorful sauces and authentic Chinese flavors.",
        "introduction": "Aromatic basmati rice stir fried with fresh vegetables, flavorful sauces and authentic Chinese flavors.",
        "category": "Rice",
        "cuisine": "Indian",
        "prepTime": "10 mins",
        "cookTime": "15 mins",
        "totalTime": "25 mins",
        "servings": 1,
        "difficulty": "Easy",
        "ingredients": [],
        "instructions": [],
        "tips": [],
        "image": "https://b.zmtcdn.com/data/dish_photos/81e/ebe8803c2625d73ffaffdd4710f1681e.png",
        "imageAlt": "Fried Rice",
        "seoTitle": "Fried Rice | Foody Bhai",
        "seoDescription": "Aromatic basmati rice stir fried with fresh vegetables, flavorful sauces and authentic Chinese flavors.",
        "isVeg": true,
        "price": 119
    },
    {
        "id": 18,
        "slug": "tawa-roti-with-butter",
        "title": "Tawa Roti with Butter",
        "description": "Soft, freshly prepared whole wheat tawa roti, generously topped with rich, melted butter.",
        "introduction": "Soft, freshly prepared whole wheat tawa roti, generously topped with rich, melted butter.",
        "category": "Everyday Essentials",
        "cuisine": "Indian",
        "prepTime": "10 mins",
        "cookTime": "15 mins",
        "totalTime": "25 mins",
        "servings": 1,
        "difficulty": "Easy",
        "ingredients": [],
        "instructions": [],
        "tips": [],
        "image": "https://b.zmtcdn.com/data/dish_photos/b86/2526b751471618ed226f11f400217b86.jpeg",
        "imageAlt": "Tawa Roti with Butter",
        "seoTitle": "Tawa Roti with Butter | Foody Bhai",
        "seoDescription": "Soft, freshly prepared whole wheat tawa roti, generously topped with rich, melted butter.",
        "isVeg": true,
        "price": 15
    },
    {
        "id": 19,
        "slug": "tawa-roti-ghee-wali",
        "title": "Tawa Roti Ghee Wali",
        "description": "Soft, freshly prepared whole wheat rotis generously brushed with pure ghee.",
        "introduction": "Soft, freshly prepared whole wheat rotis generously brushed with pure ghee.",
        "category": "Everyday Essentials",
        "cuisine": "Indian",
        "prepTime": "10 mins",
        "cookTime": "15 mins",
        "totalTime": "25 mins",
        "servings": 1,
        "difficulty": "Easy",
        "ingredients": [],
        "instructions": [],
        "tips": [],
        "image": "https://b.zmtcdn.com/data/dish_photos/b69/f232b02d1e2d1535cbf6d7b8301b2b69.jpg",
        "imageAlt": "Tawa Roti Ghee Wali",
        "seoTitle": "Tawa Roti Ghee Wali | Foody Bhai",
        "seoDescription": "Soft, freshly prepared whole wheat rotis generously brushed with pure ghee.",
        "isVeg": true,
        "price": 12
    },
    {
        "id": 20,
        "slug": "tawa-roti",
        "title": "Tawa Roti",
        "description": "Soft, thin and wholesome, tawa roti is a classic Indian flatbread made from whole wheat.",
        "introduction": "Soft, thin and wholesome, tawa roti is a classic Indian flatbread made from whole wheat.",
        "category": "Everyday Essentials",
        "cuisine": "Indian",
        "prepTime": "10 mins",
        "cookTime": "15 mins",
        "totalTime": "25 mins",
        "servings": 1,
        "difficulty": "Easy",
        "ingredients": [],
        "instructions": [],
        "tips": [],
        "image": "https://b.zmtcdn.com/data/dish_photos/494/409a3a96f6198c79d3797ed7e0069494.png",
        "imageAlt": "Tawa Roti",
        "seoTitle": "Tawa Roti | Foody Bhai",
        "seoDescription": "Soft, thin and wholesome, tawa roti is a classic Indian flatbread made from whole wheat.",
        "isVeg": true,
        "price": 10
    },
    {
        "id": 21,
        "slug": "plain-butter-paratha",
        "title": "Plain Butter Paratha",
        "description": "Plain butter paratha is a crispy and flavorful Indian flatbread generously finished with butter.",
        "introduction": "Plain butter paratha is a crispy and flavorful Indian flatbread generously finished with butter.",
        "category": "Everyday Essentials",
        "cuisine": "Indian",
        "prepTime": "10 mins",
        "cookTime": "15 mins",
        "totalTime": "25 mins",
        "servings": 1,
        "difficulty": "Easy",
        "ingredients": [],
        "instructions": [],
        "tips": [],
        "image": "https://b.zmtcdn.com/data/dish_photos/630/d3a8ef27386d796a52bc80fe6eeb6630.jpg",
        "imageAlt": "Plain Butter Paratha",
        "seoTitle": "Plain Butter Paratha | Foody Bhai",
        "seoDescription": "Plain butter paratha is a crispy and flavorful Indian flatbread generously finished with butter.",
        "isVeg": true,
        "price": 37
    },
    {
        "id": 22,
        "slug": "plain-paneer-paratha",
        "title": "Plain Paneer Paratha",
        "description": "Soft and flaky whole wheat flatbread stuffed with a mildly spiced paneer filling.",
        "introduction": "Soft and flaky whole wheat flatbread stuffed with a mildly spiced paneer filling.",
        "category": "Everyday Essentials",
        "cuisine": "Indian",
        "prepTime": "10 mins",
        "cookTime": "15 mins",
        "totalTime": "25 mins",
        "servings": 1,
        "difficulty": "Easy",
        "ingredients": [],
        "instructions": [],
        "tips": [],
        "image": "https://b.zmtcdn.com/data/dish_photos/49e/d1531de51830665b134ce5e20f55949e.jpg",
        "imageAlt": "Plain Paneer Paratha",
        "seoTitle": "Plain Paneer Paratha | Foody Bhai",
        "seoDescription": "Soft and flaky whole wheat flatbread stuffed with a mildly spiced paneer filling.",
        "isVeg": true,
        "price": 59
    },
    {
        "id": 23,
        "slug": "paneer-paratha-with-butter",
        "title": "Paneer Paratha with Butter",
        "description": "Delicious stuffed Indian flatbread filled with flavorful paneer and finished with butter.",
        "introduction": "Delicious stuffed Indian flatbread filled with flavorful paneer and finished with butter.",
        "category": "Everyday Essentials",
        "cuisine": "Indian",
        "prepTime": "10 mins",
        "cookTime": "15 mins",
        "totalTime": "25 mins",
        "servings": 1,
        "difficulty": "Easy",
        "ingredients": [],
        "instructions": [],
        "tips": [],
        "image": "https://b.zmtcdn.com/data/dish_photos/2b0/7e4f51ba13d2411841a1719e6c8c72b0.jpg",
        "imageAlt": "Paneer Paratha with Butter",
        "seoTitle": "Paneer Paratha with Butter | Foody Bhai",
        "seoDescription": "Delicious stuffed Indian flatbread filled with flavorful paneer and finished with butter.",
        "isVeg": true,
        "price": 69
    },
    {
        "id": 24,
        "slug": "aloo-paratha",
        "title": "Aloo Paratha",
        "description": "Popular North Indian flatbread stuffed with a spiced potato filling.",
        "introduction": "Popular North Indian flatbread stuffed with a spiced potato filling.",
        "category": "Everyday Essentials",
        "cuisine": "Indian",
        "prepTime": "10 mins",
        "cookTime": "15 mins",
        "totalTime": "25 mins",
        "servings": 1,
        "difficulty": "Easy",
        "ingredients": [],
        "instructions": [],
        "tips": [],
        "image": "https://b.zmtcdn.com/data/dish_photos/4dd/b3af00f71f5cb231f4b812c7353964dd.jpeg",
        "imageAlt": "Aloo Paratha",
        "seoTitle": "Aloo Paratha | Foody Bhai",
        "seoDescription": "Popular North Indian flatbread stuffed with a spiced potato filling.",
        "isVeg": true,
        "price": 56
    },
    {
        "id": 25,
        "slug": "aloo-pyaaz-paratha",
        "title": "Aloo Pyaaz Paratha",
        "description": "Popular North Indian stuffed flatbread filled with a flavorful potato and onion mixture.",
        "introduction": "Popular North Indian stuffed flatbread filled with a flavorful potato and onion mixture.",
        "category": "Everyday Essentials",
        "cuisine": "Indian",
        "prepTime": "10 mins",
        "cookTime": "15 mins",
        "totalTime": "25 mins",
        "servings": 1,
        "difficulty": "Easy",
        "ingredients": [],
        "instructions": [],
        "tips": [],
        "image": "https://b.zmtcdn.com/data/dish_photos/4dd/65bf3b264f46f0a391f47e6f72e584dd.jpg",
        "imageAlt": "Aloo Pyaaz Paratha",
        "seoTitle": "Aloo Pyaaz Paratha | Foody Bhai",
        "seoDescription": "Popular North Indian stuffed flatbread filled with a flavorful potato and onion mixture.",
        "isVeg": true,
        "price": 66
    },
    {
        "id": 26,
        "slug": "gobi-paratha",
        "title": "Gobi Paratha",
        "description": "Hearty and flavorful Indian flatbread stuffed with a spiced mixture of cauliflower.",
        "introduction": "Hearty and flavorful Indian flatbread stuffed with a spiced mixture of cauliflower.",
        "category": "Everyday Essentials",
        "cuisine": "Indian",
        "prepTime": "10 mins",
        "cookTime": "15 mins",
        "totalTime": "25 mins",
        "servings": 1,
        "difficulty": "Easy",
        "ingredients": [],
        "instructions": [],
        "tips": [],
        "image": "https://b.zmtcdn.com/data/dish_photos/6a0/ac194a6cb90fc69d8f47b9c7c1c1b6a0.jpg",
        "imageAlt": "Gobi Paratha",
        "seoTitle": "Gobi Paratha | Foody Bhai",
        "seoDescription": "Hearty and flavorful Indian flatbread stuffed with a spiced mixture of cauliflower.",
        "isVeg": true,
        "price": 72
    },
    {
        "id": 27,
        "slug": "mixed-veggie-paratha",
        "title": "Mixed Veggie Paratha",
        "description": "Soft and flaky whole wheat flatbread stuffed with a delicious mixed vegetable filling.",
        "introduction": "Soft and flaky whole wheat flatbread stuffed with a delicious mixed vegetable filling.",
        "category": "Everyday Essentials",
        "cuisine": "Indian",
        "prepTime": "10 mins",
        "cookTime": "15 mins",
        "totalTime": "25 mins",
        "servings": 1,
        "difficulty": "Easy",
        "ingredients": [],
        "instructions": [],
        "tips": [],
        "image": "https://b.zmtcdn.com/data/dish_photos/e13/4e14bd2b8e45869fd16151ebc5136e13.jpg",
        "imageAlt": "Mixed Veggie Paratha",
        "seoTitle": "Mixed Veggie Paratha | Foody Bhai",
        "seoDescription": "Soft and flaky whole wheat flatbread stuffed with a delicious mixed vegetable filling.",
        "isVeg": true,
        "price": 79
    },
    {
        "id": 28,
        "slug": "aloo-paneer-pyaaz-paratha",
        "title": "Aloo Paneer Pyaaz Paratha",
        "description": "Hearty stuffed paratha packed with a delicious mixture of mashed potato, paneer and onion.",
        "introduction": "Hearty stuffed paratha packed with a delicious mixture of mashed potato, paneer and onion.",
        "category": "Everyday Essentials",
        "cuisine": "Indian",
        "prepTime": "10 mins",
        "cookTime": "15 mins",
        "totalTime": "25 mins",
        "servings": 1,
        "difficulty": "Easy",
        "ingredients": [],
        "instructions": [],
        "tips": [],
        "image": "https://b.zmtcdn.com/data/dish_photos/542/245d02bb3283e67314a10905e9f83542.jpeg",
        "imageAlt": "Aloo Paneer Pyaaz Paratha",
        "seoTitle": "Aloo Paneer Pyaaz Paratha | Foody Bhai",
        "seoDescription": "Hearty stuffed paratha packed with a delicious mixture of mashed potato, paneer and onion.",
        "isVeg": true,
        "price": 84
    },
    {
        "id": 29,
        "slug": "royal-aloo-pyaaz-paratha",
        "title": "Royal Aloo Pyaaz Paratha",
        "description": "A king-sized delight packed with rich, flavorful mashed potatoes, aromatic spices and onion.",
        "introduction": "A king-sized delight packed with rich, flavorful mashed potatoes, aromatic spices and onion.",
        "category": "Everyday Essentials",
        "cuisine": "Indian",
        "prepTime": "10 mins",
        "cookTime": "15 mins",
        "totalTime": "25 mins",
        "servings": 1,
        "difficulty": "Easy",
        "ingredients": [],
        "instructions": [],
        "tips": [],
        "image": "https://b.zmtcdn.com/data/dish_photos/528/9a9d7bf37e8641ba304d4871c1663528.jpg",
        "imageAlt": "Royal Aloo Pyaaz Paratha",
        "seoTitle": "Royal Aloo Pyaaz Paratha | Foody Bhai",
        "seoDescription": "A king-sized delight packed with rich, flavorful mashed potatoes, aromatic spices and onion.",
        "isVeg": true,
        "price": 110
    },
    {
        "id": 30,
        "slug": "red-sauce-pasta",
        "title": "Red Sauce Pasta",
        "description": "Popular Italian-style pasta served with a rich and flavorful red tomato sauce.",
        "introduction": "Popular Italian-style pasta served with a rich and flavorful red tomato sauce.",
        "category": "Snacks",
        "cuisine": "Indian",
        "prepTime": "10 mins",
        "cookTime": "15 mins",
        "totalTime": "25 mins",
        "servings": 1,
        "difficulty": "Easy",
        "ingredients": [],
        "instructions": [],
        "tips": [],
        "image": "https://b.zmtcdn.com/data/dish_photos/fb9/d86236665754991867498eb4fdf2afb9.jpg",
        "imageAlt": "Red Sauce Pasta",
        "seoTitle": "Red Sauce Pasta | Foody Bhai",
        "seoDescription": "Popular Italian-style pasta served with a rich and flavorful red tomato sauce.",
        "isVeg": true,
        "price": 119
    },
    {
        "id": 31,
        "slug": "masala-macaroni",
        "title": "Masala Macaroni",
        "description": "Boiled macaroni saut\u00e9ed with aromatic spices and flavorful masala.",
        "introduction": "Boiled macaroni saut\u00e9ed with aromatic spices and flavorful masala.",
        "category": "Snacks",
        "cuisine": "Indian",
        "prepTime": "10 mins",
        "cookTime": "15 mins",
        "totalTime": "25 mins",
        "servings": 1,
        "difficulty": "Easy",
        "ingredients": [],
        "instructions": [],
        "tips": [],
        "image": "https://b.zmtcdn.com/data/dish_photos/7b6/52b9c30359a4f66d1dcea88849a8d7b6.jpg",
        "imageAlt": "Masala Macaroni",
        "seoTitle": "Masala Macaroni | Foody Bhai",
        "seoDescription": "Boiled macaroni saut\u00e9ed with aromatic spices and flavorful masala.",
        "isVeg": true,
        "price": 109
    },
    {
        "id": 32,
        "slug": "bhel-puri-north-indian-style-full",
        "title": "Bhel Puri North Indian Style (Full)",
        "description": "Popular tangy and flavorful North Indian-style street food snack.",
        "introduction": "Popular tangy and flavorful North Indian-style street food snack.",
        "category": "Snacks",
        "cuisine": "Indian",
        "prepTime": "10 mins",
        "cookTime": "15 mins",
        "totalTime": "25 mins",
        "servings": 1,
        "difficulty": "Easy",
        "ingredients": [],
        "instructions": [],
        "tips": [],
        "image": "https://b.zmtcdn.com/data/dish_photos/313/22ea32b1d83b742fb4d8e91a2b5fb313.jpg",
        "imageAlt": "Bhel Puri North Indian Style (Full)",
        "seoTitle": "Bhel Puri North Indian Style (Full) | Foody Bhai",
        "seoDescription": "Popular tangy and flavorful North Indian-style street food snack.",
        "isVeg": true,
        "price": 70
    },
    {
        "id": 33,
        "slug": "plain-maggi",
        "title": "Plain Maggi",
        "description": "Classic Maggi noodles loved for their quick preparation and delicious taste.",
        "introduction": "Classic Maggi noodles loved for their quick preparation and delicious taste.",
        "category": "Snacks",
        "cuisine": "Indian",
        "prepTime": "10 mins",
        "cookTime": "15 mins",
        "totalTime": "25 mins",
        "servings": 1,
        "difficulty": "Easy",
        "ingredients": [],
        "instructions": [],
        "tips": [],
        "image": "https://b.zmtcdn.com/data/dish_photos/65b/50321763a2bd9b10360105a045aa565b.png",
        "imageAlt": "Plain Maggi",
        "seoTitle": "Plain Maggi | Foody Bhai",
        "seoDescription": "Classic Maggi noodles loved for their quick preparation and delicious taste.",
        "isVeg": true,
        "price": 49
    },
    {
        "id": 34,
        "slug": "mix-veggie-maggi",
        "title": "Mix Veggie Maggi",
        "description": "Flavorful and nutritious Maggi noodles prepared with mixed vegetables and spices.",
        "introduction": "Flavorful and nutritious Maggi noodles prepared with mixed vegetables and spices.",
        "category": "Snacks",
        "cuisine": "Indian",
        "prepTime": "10 mins",
        "cookTime": "15 mins",
        "totalTime": "25 mins",
        "servings": 1,
        "difficulty": "Easy",
        "ingredients": [],
        "instructions": [],
        "tips": [],
        "image": "https://b.zmtcdn.com/data/dish_photos/a8e/9aa13209ad31ee382449c8a2902d7a8e.jpg",
        "imageAlt": "Mix Veggie Maggi",
        "seoTitle": "Mix Veggie Maggi | Foody Bhai",
        "seoDescription": "Flavorful and nutritious Maggi noodles prepared with mixed vegetables and spices.",
        "isVeg": true,
        "price": 89
    },
    {
        "id": 35,
        "slug": "mix-veg-maggie-with-butter",
        "title": "Mix Veg Maggie with Butter",
        "description": "Hot and delicious Maggi noodles tossed with fresh mixed vegetables, aromatic spices and butter.",
        "introduction": "Hot and delicious Maggi noodles tossed with fresh mixed vegetables, aromatic spices and butter.",
        "category": "Snacks",
        "cuisine": "Indian",
        "prepTime": "10 mins",
        "cookTime": "15 mins",
        "totalTime": "25 mins",
        "servings": 1,
        "difficulty": "Easy",
        "ingredients": [],
        "instructions": [],
        "tips": [],
        "image": "https://b.zmtcdn.com/data/dish_photos/a4a/b6d6254d66744ec2a117732a52a09a4a.jpg",
        "imageAlt": "Mix Veg Maggie with Butter",
        "seoTitle": "Mix Veg Maggie with Butter | Foody Bhai",
        "seoDescription": "Hot and delicious Maggi noodles tossed with fresh mixed vegetables, aromatic spices and butter.",
        "isVeg": true,
        "price": 119
    },
    {
        "id": 36,
        "slug": "peri-peri-maggi",
        "title": "Peri Peri Maggi",
        "description": "Hot and delicious Maggi noodles tossed with bold peri peri seasoning and aromatic spices.",
        "introduction": "Hot and delicious Maggi noodles tossed with bold peri peri seasoning and aromatic spices.",
        "category": "Snacks",
        "cuisine": "Indian",
        "prepTime": "10 mins",
        "cookTime": "15 mins",
        "totalTime": "25 mins",
        "servings": 1,
        "difficulty": "Easy",
        "ingredients": [],
        "instructions": [],
        "tips": [],
        "image": "https://b.zmtcdn.com/data/dish_photos/49d/aa15b854453ff6e9de7671981633e49d.jpg",
        "imageAlt": "Peri Peri Maggi",
        "seoTitle": "Peri Peri Maggi | Foody Bhai",
        "seoDescription": "Hot and delicious Maggi noodles tossed with bold peri peri seasoning and aromatic spices.",
        "isVeg": true,
        "price": 110
    },
    {
        "id": 37,
        "slug": "fresh-kheera-tomato-onion-salad",
        "title": "Fresh Kheera, Tomato & Onion Salad",
        "description": "Freshly sliced cucumber, juicy tomatoes and onion rings, lightly seasoned and served fresh.",
        "introduction": "Freshly sliced cucumber, juicy tomatoes and onion rings, lightly seasoned and served fresh.",
        "category": "Fresh Salad",
        "cuisine": "Indian",
        "prepTime": "10 mins",
        "cookTime": "15 mins",
        "totalTime": "25 mins",
        "servings": 1,
        "difficulty": "Easy",
        "ingredients": [],
        "instructions": [],
        "tips": [],
        "image": "https://b.zmtcdn.com/data/dish_photos/7f6/a5120f06f9a941e2579d1d632d5047f6.jpeg",
        "imageAlt": "Fresh Kheera, Tomato & Onion Salad",
        "seoTitle": "Fresh Kheera, Tomato & Onion Salad | Foody Bhai",
        "seoDescription": "Freshly sliced cucumber, juicy tomatoes and onion rings, lightly seasoned and served fresh.",
        "isVeg": true,
        "price": 29
    },
    {
        "id": 38,
        "slug": "kheera-salad",
        "title": "Kheera Salad",
        "description": "Freshly sliced cucumber, lightly seasoned and served fresh.",
        "introduction": "Freshly sliced cucumber, lightly seasoned and served fresh.",
        "category": "Fresh Salad",
        "cuisine": "Indian",
        "prepTime": "10 mins",
        "cookTime": "15 mins",
        "totalTime": "25 mins",
        "servings": 1,
        "difficulty": "Easy",
        "ingredients": [],
        "instructions": [],
        "tips": [],
        "image": "https://b.zmtcdn.com/data/dish_photos/f88/d53227dd915a9fd05f157091f267ef88.jpeg",
        "imageAlt": "Kheera Salad",
        "seoTitle": "Kheera Salad | Foody Bhai",
        "seoDescription": "Freshly sliced cucumber, lightly seasoned and served fresh.",
        "isVeg": true,
        "price": 29
    },
    {
        "id": 39,
        "slug": "onion-salad",
        "title": "Onion Salad",
        "description": "Fresh onion rings served with light seasoning.",
        "introduction": "Fresh onion rings served with light seasoning.",
        "category": "Fresh Salad",
        "cuisine": "Indian",
        "prepTime": "10 mins",
        "cookTime": "15 mins",
        "totalTime": "25 mins",
        "servings": 1,
        "difficulty": "Easy",
        "ingredients": [],
        "instructions": [],
        "tips": [],
        "image": "https://b.zmtcdn.com/data/dish_photos/edf/900d2b4d20761f27a1391634d792eedf.jpeg",
        "imageAlt": "Onion Salad",
        "seoTitle": "Onion Salad | Foody Bhai",
        "seoDescription": "Fresh onion rings served with light seasoning.",
        "isVeg": true,
        "price": 29
    },
    {
        "id": 40,
        "slug": "tomato-salad",
        "title": "Tomato Salad",
        "description": "Juicy tomato slices, freshly cut and lightly seasoned.",
        "introduction": "Juicy tomato slices, freshly cut and lightly seasoned.",
        "category": "Fresh Salad",
        "cuisine": "Indian",
        "prepTime": "10 mins",
        "cookTime": "15 mins",
        "totalTime": "25 mins",
        "servings": 1,
        "difficulty": "Easy",
        "ingredients": [],
        "instructions": [],
        "tips": [],
        "image": "https://b.zmtcdn.com/data/dish_photos/525/b8a74d30f3de9ffd504eee9a7493a525.jpeg",
        "imageAlt": "Tomato Salad",
        "seoTitle": "Tomato Salad | Foody Bhai",
        "seoDescription": "Juicy tomato slices, freshly cut and lightly seasoned.",
        "isVeg": true,
        "price": 29
    },
    {
        "id": 41,
        "slug": "boondi-raita",
        "title": "Boondi Raita",
        "description": "Creamy yogurt mixed with crispy boondi and seasoned with roasted cumin and black salt.",
        "introduction": "Creamy yogurt mixed with crispy boondi and seasoned with roasted cumin and black salt.",
        "category": "Raita And Sides",
        "cuisine": "Indian",
        "prepTime": "10 mins",
        "cookTime": "15 mins",
        "totalTime": "25 mins",
        "servings": 1,
        "difficulty": "Easy",
        "ingredients": [],
        "instructions": [],
        "tips": [],
        "image": "https://b.zmtcdn.com/data/dish_photos/b5f/bce0832a5e8ed27a46ffe9bb8f716b5f.png",
        "imageAlt": "Boondi Raita",
        "seoTitle": "Boondi Raita | Foody Bhai",
        "seoDescription": "Creamy yogurt mixed with crispy boondi and seasoned with roasted cumin and black salt.",
        "isVeg": true,
        "price": 45
    },
    {
        "id": 42,
        "slug": "mix-veg-raita",
        "title": "Mix Veg Raita",
        "description": "Thick, chilled yogurt blended with fresh cucumber, onion, tomato and mild Indian spices.",
        "introduction": "Thick, chilled yogurt blended with fresh cucumber, onion, tomato and mild Indian spices.",
        "category": "Raita And Sides",
        "cuisine": "Indian",
        "prepTime": "10 mins",
        "cookTime": "15 mins",
        "totalTime": "25 mins",
        "servings": 1,
        "difficulty": "Easy",
        "ingredients": [],
        "instructions": [],
        "tips": [],
        "image": "https://b.zmtcdn.com/data/dish_photos/4d7/603dd35d1ee3d715a4917cc2c81424d7.png",
        "imageAlt": "Mix Veg Raita",
        "seoTitle": "Mix Veg Raita | Foody Bhai",
        "seoDescription": "Thick, chilled yogurt blended with fresh cucumber, onion, tomato and mild Indian spices.",
        "isVeg": true,
        "price": 59
    },
    {
        "id": 43,
        "slug": "plain-raita",
        "title": "Plain Raita",
        "description": "Smooth and creamy chilled yogurt lightly seasoned with roasted cumin and a pinch of spices.",
        "introduction": "Smooth and creamy chilled yogurt lightly seasoned with roasted cumin and a pinch of spices.",
        "category": "Raita And Sides",
        "cuisine": "Indian",
        "prepTime": "10 mins",
        "cookTime": "15 mins",
        "totalTime": "25 mins",
        "servings": 1,
        "difficulty": "Easy",
        "ingredients": [],
        "instructions": [],
        "tips": [],
        "image": "https://b.zmtcdn.com/data/dish_photos/775/21aa04db95d3e6137e4dcfa704d47775.png",
        "imageAlt": "Plain Raita",
        "seoTitle": "Plain Raita | Foody Bhai",
        "seoDescription": "Smooth and creamy chilled yogurt lightly seasoned with roasted cumin and a pinch of spices.",
        "isVeg": true,
        "price": 39
    },
    {
        "id": 44,
        "slug": "masala-shikanji",
        "title": "Masala Shikanji",
        "description": "Traditional Indian lemonade made with fresh lemon juice, chilled water and refreshing spices.",
        "introduction": "Traditional Indian lemonade made with fresh lemon juice, chilled water and refreshing spices.",
        "category": "Drinks & Beverages",
        "cuisine": "Indian",
        "prepTime": "10 mins",
        "cookTime": "15 mins",
        "totalTime": "25 mins",
        "servings": 1,
        "difficulty": "Easy",
        "ingredients": [],
        "instructions": [],
        "tips": [],
        "image": "https://b.zmtcdn.com/data/dish_photos/a47/93ca564612cfa241bc2e8ddc72db1a47.jpeg",
        "imageAlt": "Masala Shikanji",
        "seoTitle": "Masala Shikanji | Foody Bhai",
        "seoDescription": "Traditional Indian lemonade made with fresh lemon juice, chilled water and refreshing spices.",
        "isVeg": true,
        "price": 30
    },
    {
        "id": 45,
        "slug": "dal-chawal-combo",
        "title": "Dal Chawal Combo",
        "description": "A well-balanced and nutritious meal of flavorful dal served with rice.",
        "introduction": "A well-balanced and nutritious meal of flavorful dal served with rice.",
        "category": "Special Combos",
        "cuisine": "Indian",
        "prepTime": "10 mins",
        "cookTime": "15 mins",
        "totalTime": "25 mins",
        "servings": 1,
        "difficulty": "Easy",
        "ingredients": [],
        "instructions": [],
        "tips": [],
        "image": "https://b.zmtcdn.com/data/dish_photos/e3c/87fa4cf53ba6eb8efc28fd7581868e3c.jpeg",
        "imageAlt": "Dal Chawal Combo",
        "seoTitle": "Dal Chawal Combo | Foody Bhai",
        "seoDescription": "A well-balanced and nutritious meal of flavorful dal served with rice.",
        "isVeg": true,
        "price": 239
    },
    {
        "id": 46,
        "slug": "dal-with-4-roti",
        "title": "Dal with 4 Roti",
        "description": "A filling and comforting combination of flavorful dal served with 4 freshly prepared rotis.",
        "introduction": "A filling and comforting combination of flavorful dal served with 4 freshly prepared rotis.",
        "category": "Special Combos",
        "cuisine": "Indian",
        "prepTime": "10 mins",
        "cookTime": "15 mins",
        "totalTime": "25 mins",
        "servings": 1,
        "difficulty": "Easy",
        "ingredients": [],
        "instructions": [],
        "tips": [],
        "image": "https://b.zmtcdn.com/data/dish_photos/a95/57f72046ee6767b8d2973f093b0fda95.jpeg",
        "imageAlt": "Dal with 4 Roti",
        "seoTitle": "Dal with 4 Roti | Foody Bhai",
        "seoDescription": "A filling and comforting combination of flavorful dal served with 4 freshly prepared rotis.",
        "isVeg": true,
        "price": 209
    },
    {
        "id": 47,
        "slug": "dal-with-chawal-and-4-roti",
        "title": "Dal with Chawal and 4 Roti",
        "description": "Wholesome Indian meal featuring flavorful yellow dal, rice and 4 freshly prepared rotis.",
        "introduction": "Wholesome Indian meal featuring flavorful yellow dal, rice and 4 freshly prepared rotis.",
        "category": "Special Combos",
        "cuisine": "Indian",
        "prepTime": "10 mins",
        "cookTime": "15 mins",
        "totalTime": "25 mins",
        "servings": 1,
        "difficulty": "Easy",
        "ingredients": [],
        "instructions": [],
        "tips": [],
        "image": "https://b.zmtcdn.com/data/dish_photos/092/428c3cd80b4d6e4e166014332de1b092.jpeg",
        "imageAlt": "Dal with Chawal and 4 Roti",
        "seoTitle": "Dal with Chawal and 4 Roti | Foody Bhai",
        "seoDescription": "Wholesome Indian meal featuring flavorful yellow dal, rice and 4 freshly prepared rotis.",
        "isVeg": true,
        "price": 289
    },
    {
        "id": 48,
        "slug": "paneer-butter-masala-with-4-roti",
        "title": "Paneer Butter Masala with 4 Roti",
        "description": "Rich and creamy paneer butter masala served with 4 freshly prepared rotis.",
        "introduction": "Rich and creamy paneer butter masala served with 4 freshly prepared rotis.",
        "category": "Special Combos",
        "cuisine": "Indian",
        "prepTime": "10 mins",
        "cookTime": "15 mins",
        "totalTime": "25 mins",
        "servings": 1,
        "difficulty": "Easy",
        "ingredients": [],
        "instructions": [],
        "tips": [],
        "image": "https://b.zmtcdn.com/data/dish_photos/605/c556a7487ca4680a960464f2943bc605.jpg",
        "imageAlt": "Paneer Butter Masala with 4 Roti",
        "seoTitle": "Paneer Butter Masala with 4 Roti | Foody Bhai",
        "seoDescription": "Rich and creamy paneer butter masala served with 4 freshly prepared rotis.",
        "isVeg": true,
        "price": 249
    },
    {
        "id": 49,
        "slug": "aloo-jeera-masala-with-raita-and-4-roti",
        "title": "Aloo Jeera Masala With Raita and 4 Roti",
        "description": "Flavorful aloo jeera masala served with creamy raita and 4 soft, freshly prepared rotis.",
        "introduction": "Flavorful aloo jeera masala served with creamy raita and 4 soft, freshly prepared rotis.",
        "category": "Special Combos",
        "cuisine": "Indian",
        "prepTime": "10 mins",
        "cookTime": "15 mins",
        "totalTime": "25 mins",
        "servings": 1,
        "difficulty": "Easy",
        "ingredients": [],
        "instructions": [],
        "tips": [],
        "image": "https://b.zmtcdn.com/data/dish_photos/e03/88e4577157e2d424c363e55e2d8f7e03.jpg",
        "imageAlt": "Aloo Jeera Masala With Raita and 4 Roti",
        "seoTitle": "Aloo Jeera Masala With Raita and 4 Roti | Foody Bhai",
        "seoDescription": "Flavorful aloo jeera masala served with creamy raita and 4 soft, freshly prepared rotis.",
        "isVeg": true,
        "price": 139
    },
    {
        "id": 50,
        "slug": "red-sauce-pasta-macroni",
        "title": "Red Sauce Pasta + Macroni",
        "description": "Delicious pasta and macaroni tossed in a rich, tangy red tomato sauce.",
        "introduction": "Delicious pasta and macaroni tossed in a rich, tangy red tomato sauce.",
        "category": "Special Combos",
        "cuisine": "Indian",
        "prepTime": "10 mins",
        "cookTime": "15 mins",
        "totalTime": "25 mins",
        "servings": 1,
        "difficulty": "Easy",
        "ingredients": [],
        "instructions": [],
        "tips": [],
        "image": "https://b.zmtcdn.com/data/dish_photos/3e6/7285238fdd8e70920b4fed76346743e6.jpg",
        "imageAlt": "Red Sauce Pasta + Macroni",
        "seoTitle": "Red Sauce Pasta + Macroni | Foody Bhai",
        "seoDescription": "Delicious pasta and macaroni tossed in a rich, tangy red tomato sauce.",
        "isVeg": true,
        "price": 149
    },
    {
        "id": 51,
        "slug": "paneer-masala-4-roti-salad",
        "title": "Paneer Masala + 4 Roti + Salad",
        "description": "Flavorful paneer masala served with 4 freshly made rotis and fresh salad.",
        "introduction": "Flavorful paneer masala served with 4 freshly made rotis and fresh salad.",
        "category": "Thalis And Mini Meals",
        "cuisine": "Indian",
        "prepTime": "10 mins",
        "cookTime": "15 mins",
        "totalTime": "25 mins",
        "servings": 1,
        "difficulty": "Easy",
        "ingredients": [],
        "instructions": [],
        "tips": [],
        "image": "https://b.zmtcdn.com/data/dish_photos/15d/9efe37a00f9f3cc5c9add21a2c7e315d.jpg",
        "imageAlt": "Paneer Masala + 4 Roti + Salad",
        "seoTitle": "Paneer Masala + 4 Roti + Salad | Foody Bhai",
        "seoDescription": "Flavorful paneer masala served with 4 freshly made rotis and fresh salad.",
        "isVeg": true,
        "price": 139
    },
    {
        "id": 52,
        "slug": "dal-4-roti-jeera-aloo-salad",
        "title": "Dal + 4 Roti + Jeera Aloo + Salad",
        "description": "Wholesome meal featuring homestyle dal, 4 freshly made rotis, jeera aloo and salad.",
        "introduction": "Wholesome meal featuring homestyle dal, 4 freshly made rotis, jeera aloo and salad.",
        "category": "Thalis And Mini Meals",
        "cuisine": "Indian",
        "prepTime": "10 mins",
        "cookTime": "15 mins",
        "totalTime": "25 mins",
        "servings": 1,
        "difficulty": "Easy",
        "ingredients": [],
        "instructions": [],
        "tips": [],
        "image": "https://b.zmtcdn.com/data/dish_photos/abe/8ff705e448f6e47d260ad1c9607bdabe.jpg",
        "imageAlt": "Dal + 4 Roti + Jeera Aloo + Salad",
        "seoTitle": "Dal + 4 Roti + Jeera Aloo + Salad | Foody Bhai",
        "seoDescription": "Wholesome meal featuring homestyle dal, 4 freshly made rotis, jeera aloo and salad.",
        "isVeg": true,
        "price": 169
    },
    {
        "id": 53,
        "slug": "dal-chawal-salad",
        "title": "Dal + Chawal + Salad",
        "description": "Comforting and wholesome meal of flavorful homestyle dal served with freshly cooked rice and salad.",
        "introduction": "Comforting and wholesome meal of flavorful homestyle dal served with freshly cooked rice and salad.",
        "category": "Thalis And Mini Meals",
        "cuisine": "Indian",
        "prepTime": "10 mins",
        "cookTime": "15 mins",
        "totalTime": "25 mins",
        "servings": 1,
        "difficulty": "Easy",
        "ingredients": [],
        "instructions": [],
        "tips": [],
        "image": "https://b.zmtcdn.com/data/dish_photos/343/23a8f00660e5c5acc9047404cb3fb343.jpeg",
        "imageAlt": "Dal + Chawal + Salad",
        "seoTitle": "Dal + Chawal + Salad | Foody Bhai",
        "seoDescription": "Comforting and wholesome meal of flavorful homestyle dal served with freshly cooked rice and salad.",
        "isVeg": true,
        "price": 159
    }
];

  getCategories(): {name: string, slug: string, description: string, icon: string}[] {
    return [
    {
        "name": "Main Course",
        "slug": "main-course",
        "description": "Delicious Main Course options from Foody Bhai.",
        "icon": "fa-solid fa-bowl-food"
    },
    {
        "name": "Puri & Sabzi",
        "slug": "puri-sabzi",
        "description": "Delicious Puri & Sabzi options from Foody Bhai.",
        "icon": "fa-solid fa-bread-slice"
    },
    {
        "name": "Rice",
        "slug": "rice",
        "description": "Delicious Rice options from Foody Bhai.",
        "icon": "fa-solid fa-bowl-rice"
    },
    {
        "name": "Everyday Essentials",
        "slug": "everyday-essentials",
        "description": "Delicious Everyday Essentials options from Foody Bhai.",
        "icon": "fa-solid fa-basket-shopping"
    },
    {
        "name": "Snacks",
        "slug": "snacks",
        "description": "Delicious Snacks options from Foody Bhai.",
        "icon": "fa-solid fa-cookie-bite"
    },
    {
        "name": "Fresh Salad",
        "slug": "fresh-salad",
        "description": "Delicious Fresh Salad options from Foody Bhai.",
        "icon": "fa-solid fa-leaf"
    },
    {
        "name": "Raita And Sides",
        "slug": "raita-and-sides",
        "description": "Delicious Raita And Sides options from Foody Bhai.",
        "icon": "fa-solid fa-spoon"
    },
    {
        "name": "Drinks & Beverages",
        "slug": "drinks-beverages",
        "description": "Delicious Drinks & Beverages options from Foody Bhai.",
        "icon": "fa-solid fa-mug-hot"
    },
    {
        "name": "Special Combos",
        "slug": "special-combos",
        "description": "Delicious Special Combos options from Foody Bhai.",
        "icon": "fa-solid fa-boxes-stacked"
    },
    {
        "name": "Thalis And Mini Meals",
        "slug": "thalis-and-mini-meals",
        "description": "Delicious Thalis And Mini Meals options from Foody Bhai.",
        "icon": "fa-solid fa-utensils"
    }
];
  }

  getRecipes() {
    return of(this.recipes);
  }

  getRecipeBySlug(slug: string) {
    return of(this.recipes.find(r => r.slug === slug));
  }
  
  getRecipesByCategory(category: string) {
    return of(this.recipes.filter(r => r.category.toLowerCase() === category.toLowerCase()));
  }
}
