name: Deploy Angular to Hostinger

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          
      # FRONTEND BUILD & DEPLOY
      - name: Install Frontend dependencies
        run: npm ci
        working-directory: ./frontend
        
      - name: Build Frontend
        run: npm run build -- --configuration production
        working-directory: ./frontend
        
      - name: Deploy Frontend to Hostinger via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: frontend/dist/foody-bhai/browser/
          
      # ADMIN APP BUILD & DEPLOY
      - name: Install Admin App dependencies
        run: npm ci
        working-directory: ./admin-app
        
      - name: Build Admin App
        run: npm run build -- --configuration production
        working-directory: ./admin-app
        
      - name: Deploy Admin App to Hostinger via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: admin-app/dist/admin-app/
          server-dir: ./admin/
